try
{
    RemoteCalculator.Add( 1, 2 );
}
catch ( Exception ex )
{
    Console.WriteLine( ex );
}